---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: True
  vars_files:
      -  vars/main.yml

  tasks:


  pre_tasks:
   []


  roles:
    - { role: percona, tags: ['mysql'] }
    - { role: replication, when: "'replica' in group_names", tags: [ 'repl' ] }


  post_tasks:
   []
